PRODUCT_PACKAGES += \
    AccessibilityMenuOverlayProduct \
    AvatarPickerPixelOverlay \
    BuiltInPrintServiceOverlayProduct \
    CaptivePortalLoginOverlayProduct \
    CellBroadcastReceiverOverlay \
    CellBroadcastServiceOverlay \
    ContactsProviderOverlayProduct \
    FrameworkResOverlayProduct \
    GlanceableHubConfigOverlay \
    GlanceableHubSettingsConfigOverlay \
    GlanceableHubSettingsConfigOverlay2022 \
    GlanceableHubSysuiConfigOverlay \
    GoogleConfigOverlay \
    GoogleDeviceLockControllerOverlay \
    GooglePermissionControllerOverlay \
    GooglePermissionControllerSafetyCenterOverlay \
    GoogleWebViewOverlay \
    ManagedProvisioningPixelOverlay \
    MediaProviderOverlay \
    PixelConfigOverlay2018 \
    PixelConfigOverlay2019 \
    PixelConfigOverlay2019Midyear \
    PixelConfigOverlay2021 \
    PixelConfigOverlayCommon \
    PixelDocumentsUIGoogleOverlay \
    PixelSetupWizardOverlayExpressive \
    SettingsGoogleOverlayProduct \
    SettingsProviderOverlayProduct \
    SystemUIGXOverlay \
    SystemUIGoogleOverlayProduct \
    TeleServiceOverlayProduct \
    UdfpsOverlay
